### ISSUE TITLE
Search/Replace replacing extra characters

### ISSUE THREAD

**Issue by Italic-** [trentinfrederick/item-panel#1]
Hi Proxe. I just recently got your updated version of item renamer and found some issues with search/replace. I have a series of bones labelled along the lines of "lidLower.04-GRP.L" - I search and replace ".L" with ".R" and it returns the name as "li.Rower.04-GRP.R" - It does replace ".L" but it also replaced "dL" which is obviously not what I searched for. meta-androcto also made some modifications in his bpy repo you might want to talk to him about. You can find his version here: https://github.com/meta-androcto/blenderpython

meta and I hang out in IRC #blenderpython daily, so feel free to drop in and bug us about it.

**Comment by trentinfrederick** [comment]
This is because I provided python regular expressions in the find and replace fields, where the '.' in RE is a metacharacter, it is used to match any character that follows it. To match a literal dot, you need to escape it, so \.

I do believe the tool tip mentions python regular expressions are evaluated, offering much more powerful searchability at the small cost of things such as this. easy to overlook.

**Comment by trentinfrederick** [comment]
Thanks though, found my old armature data add-on in that repo 😊 can start working on it again.

**Comment by trentinfrederick** [comment]
Interesting, you have to escape with \.

Same goes for all python RE metacharacters

**Comment by trentinfrederick** [comment]
Haha, ok, \\.

**Comment by trentinfrederick** [comment]
Forgot to escape the escape character in these comments

**Comment by trentinfrederick** [comment]
Strange that it would remove the 'd', I wonder if this is a python RE error? I am unable to reproduce the same results.
